# Generated by Django 6.0.5 on 2026-05-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('registration_status', models.CharField(default='Open', max_length=20)),
            ],
        ),
    ]
